/** Minimal Better Stack API client for the scripts. */
import fs from 'node:fs';
import path from 'node:path';

export const ROOT = path.resolve(import.meta.dirname ?? __dirname, '..', '..');
export const STATE_FILE = path.join(ROOT, '.bs-state.json');
export const ENV_BS_FILE = path.join(ROOT, '.env.bs');

export function loadDotEnv(file = path.join(ROOT, '.env')): void {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!m || line.trim().startsWith('#')) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    if (process.env[m[1]] === undefined) process.env[m[1]] = v;
  }
}

export function token(): string {
  const t = process.env.BETTER_STACK_API_TOKEN;
  if (!t) throw new Error('BETTER_STACK_API_TOKEN missing (put it in .env)');
  return t;
}

export const PREFIX = process.env.BS_RESOURCE_PREFIX ?? 'bsdemo';

export interface ApiOpts {
  method?: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  body?: unknown;
  /** Return null instead of throwing for these statuses */
  allow?: number[];
}

export async function api<T = any>(base: string, p: string, opts: ApiOpts = {}): Promise<T> {
  const res = await fetch(`${base}${p}`, {
    method: opts.method ?? 'GET',
    headers: { Authorization: `Bearer ${token()}`, 'Content-Type': 'application/json', Accept: 'application/json' },
    body: opts.body === undefined ? undefined : JSON.stringify(opts.body),
  });
  const text = await res.text();
  let data: any = text;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    /* raw */
  }
  if (!res.ok) {
    if (opts.allow?.includes(res.status)) return null as T;
    throw new Error(`${opts.method ?? 'GET'} ${base}${p} -> ${res.status}: ${typeof data === 'string' ? data.slice(0, 300) : JSON.stringify(data).slice(0, 500)}`);
  }
  return data as T;
}

export const uptime = <T = any>(p: string, o?: ApiOpts) => api<T>('https://uptime.betterstack.com', p, o);
export const telemetry = <T = any>(p: string, o?: ApiOpts) => api<T>('https://telemetry.betterstack.com', p, o);
export const errors = <T = any>(p: string, o?: ApiOpts) => api<T>('https://errors.betterstack.com', p, o);

/** Walks a paginated list and returns all `data` items. */
export async function listAll(base: string, p: string, maxPages = 20): Promise<any[]> {
  const items: any[] = [];
  let url: string | null = p;
  let pages = 0;
  while (url && pages < maxPages) {
    const page: any = await api(base, url);
    items.push(...(page?.data ?? []));
    const next: string | null = page?.pagination?.next ?? null;
    url = next ? next.replace(base, '') : null;
    pages += 1;
  }
  return items;
}

export interface State {
  teamName?: string;
  source?: { id: string; token: string; ingesting_host: string; table_name: string; team_id?: number };
  collector?: { id: string; secret: string; source_id?: string };
  apps?: Record<string, { id: string; token: string; js_tag_token: string; ingesting_host: string; platform: string }>;
  urgency?: { id: string };
  policy?: { id: string };
  heartbeat?: { id: string; url: string };
  monitorGroup?: { id: string };
  monitors?: Record<string, { id: string; url: string }>;
  statusPage?: { id: string; subdomain: string; sections?: Record<string, string>; resources?: Record<string, string> };
  connection?: { id: string; host: string; username: string; password: string; tables?: Record<string, string> };
  dashboard?: { id: string; charts?: Record<string, string> };
  alerts?: Record<string, string>;
  publicUrl?: string;
}

export function readState(): State {
  return fs.existsSync(STATE_FILE) ? (JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')) as State) : {};
}

export function writeState(state: State): void {
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + '\n');
}

export function writeEnvBs(vars: Record<string, string | undefined>): void {
  const lines = ['# GENERATED by scripts/bs-setup.ts - do not commit. Used via: docker compose --env-file .env.bs ...'];
  // quote values with spaces so the file works for both `docker compose --env-file` and `source .env.bs`
  for (const [k, v] of Object.entries(vars)) lines.push(`${k}=${/[\s#]/.test(v ?? '') ? JSON.stringify(v) : (v ?? '')}`);
  fs.writeFileSync(ENV_BS_FILE, lines.join('\n') + '\n');
}

export function log(msg: string, extra?: unknown): void {
  console.log(`• ${msg}${extra !== undefined ? ' ' + (typeof extra === 'string' ? extra : JSON.stringify(extra)) : ''}`);
}

export function tunnelUrlFromDocker(): string | undefined {
  try {
    const { execSync } = require('node:child_process') as typeof import('node:child_process');
    const out = execSync('docker compose --env-file .env.bs logs --no-log-prefix --no-color tunnel 2>/dev/null || true', { cwd: ROOT, encoding: 'utf8' });
    const matches = out.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/g);
    return matches?.length ? matches[matches.length - 1] : undefined;
  } catch {
    return undefined;
  }
}
